inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  DisabledByDefault: false
  NewCops: disable
  SuggestExtensions: true

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
